import { useEffect, useMemo, useRef, useState } from 'react';
import './Music.css';

const EMPTY_ART = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 400"%3E%3Crect width="400" height="400" fill="%23141920"/%3E%3Ccircle cx="200" cy="200" r="106" fill="%23273343"/%3E%3Ccircle cx="200" cy="200" r="22" fill="%23d6ff62"/%3E%3C/svg%3E';
const time = (value = 0) => Number.isFinite(value) ? `${Math.floor(value / 60)}:${String(Math.floor(value % 60)).padStart(2, '0')}` : '0:00';

export default function Music() {
  const audio = useRef(null);
  const urls = useRef(new Set());
  const [tracks, setTracks] = useState([]); const [currentId, setCurrentId] = useState(null);
  const [playing, setPlaying] = useState(false); const [progress, setProgress] = useState(0); const [duration, setDuration] = useState(0);
  const [query, setQuery] = useState(''); const [liked, setLiked] = useState(new Set());
  const [sourceStatus, setSourceStatus] = useState('Not checked'); const [sources, setSources] = useState([]);
  const current = tracks.find((track) => track.id === currentId);
  const visible = useMemo(() => tracks.filter((track) => track.title.toLowerCase().includes(query.trim().toLowerCase())), [tracks, query]);
  useEffect(() => () => urls.current.forEach((url) => URL.revokeObjectURL(url)), []);
  useEffect(() => { if (!audio.current || !current) return; audio.current.src = current.url; audio.current.load(); if (playing) audio.current.play().catch(() => setPlaying(false)); }, [currentId]);
  const select = (id) => { setCurrentId(id); setPlaying(true); };
  const next = () => { const index = tracks.findIndex((track) => track.id === currentId); if (tracks.length) select(tracks[(index + 1 + tracks.length) % tracks.length].id); };
  const toggle = () => { if (!current && tracks[0]) return select(tracks[0].id); if (playing) audio.current?.pause(); else audio.current?.play().catch(() => setPlaying(false)); };
  const like = (id) => setLiked((value) => { const nextValue = new Set(value); nextValue.has(id) ? nextValue.delete(id) : nextValue.add(id); return nextValue; });
  const addFiles = (event) => { const added = Array.from(event.target.files || []).map((file) => { const url = URL.createObjectURL(file); urls.current.add(url); return { id: crypto.randomUUID(), title: file.name.replace(/\.[^.]+$/, '').replace(/[._-]+/g, ' '), artist: 'Local preview', url, art: EMPTY_ART }; }); setTracks((value) => [...value, ...added]); if (!currentId && added[0]) setCurrentId(added[0].id); event.target.value = ''; };
  const checkSources = async () => { setSourceStatus('Checking...'); try { const response = await fetch('/api/music/sources'); if (!response.ok) throw Error(); const payload = await response.json(); setSources(payload.sources || []); setSourceStatus(`${payload.sources?.length || 0} extensions found`); } catch { setSourceStatus('Update service not deployed'); } };
  useEffect(() => { checkSources(); }, []);
  return <main className="music-page"><audio ref={audio} onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)} onTimeUpdate={(event) => setProgress(event.currentTarget.currentTime)} onLoadedMetadata={(event) => setDuration(event.currentTarget.duration)} onEnded={next} />
    <section className="music-shell"><aside className="music-sidebar"><p className="music-brand">LURI / MUSIC</p><button className="music-nav active">Discover</button><button className="music-nav">Liked tracks <span>{liked.size}</span></button><div className="music-divider" /><label className="music-upload"><input type="file" accept="audio/*" multiple onChange={addFiles} />Preview local files</label><p className="music-note">Files remain in this browser session and are never uploaded.</p><div className="music-source-card"><span>Extension catalog</span><strong>{sourceStatus}</strong><button onClick={checkSources}>Check GitHub updates</button></div></aside>
      <section className="music-content"><header className="music-header"><div><p className="music-kicker">PERSONAL LISTENING SPACE</p><h1>Music</h1></div><label className="music-search"><span>Search</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter current queue" /></label></header>
        <div className="now-playing"><img src={current?.art || EMPTY_ART} alt="Current artwork" /><div className="now-playing__copy"><p>Now playing</p><h2>{current?.title || 'Preview an audio file'}</h2><span>{current?.artist || 'Build your listening queue'}</span></div><button className={`like-button${current && liked.has(current.id) ? ' liked' : ''}`} disabled={!current} onClick={() => current && like(current.id)}>Like</button></div>
        <div className="music-list-head"><span>Play queue</span><small>{visible.length} tracks</small></div><div className="music-list">{visible.map((track, index) => <button key={track.id} className={`music-row${track.id === currentId ? ' current' : ''}`} onClick={() => select(track.id)}><span className="track-index">{track.id === currentId && playing ? 'On' : String(index + 1).padStart(2, '0')}</span><img src={track.art} alt="" /><span className="track-title">{track.title}<small>{track.artist}</small></span><span className="track-action" onClick={(event) => { event.stopPropagation(); like(track.id); }}>{liked.has(track.id) ? 'Yes' : 'Add'}</span></button>)}{!visible.length && <div className="music-empty"><strong>No tracks yet</strong><span>Preview audio files or deploy the extension catalog to begin.</span></div>}</div>{sources.length > 0 && <p className="source-summary">Discovered extensions: {sources.map((source) => source.name).join(' / ')}</p>}</section></section>
    <footer className="music-player"><div className="music-player__song"><img src={current?.art || EMPTY_ART} alt="" /><span>{current?.title || 'No track selected'}<small>{current?.artist || 'LURI MUSIC'}</small></span></div><div className="music-controls"><div><button onClick={() => { const index = tracks.findIndex((track) => track.id === currentId); if (tracks.length) select(tracks[(index - 1 + tracks.length) % tracks.length].id); }}>Prev</button><button className="play-button" onClick={toggle}>{playing ? 'Pause' : 'Play'}</button><button onClick={next}>Next</button></div><div className="timeline"><span>{time(progress)}</span><input type="range" min="0" max={duration || 0} value={Math.min(progress, duration || 0)} onChange={(event) => { const value = Number(event.target.value); if (audio.current) audio.current.currentTime = value; setProgress(value); }} /><span>{time(duration)}</span></div></div></footer>
  </main>;
}
