import { useCallback, useEffect, useState } from 'react';
import Turnstile from './Turnstile';
import { LoadingScreen, Spinner, Toast } from './UiFeedback';
import './admin-netease.css';
import './admin-ux.css';
import './code-management.css';
import './ui-feedback.css';

const api = async (path, options = {}) => { const response = await fetch(`/api/luri-music/${path}`, { credentials: 'same-origin', headers: { 'content-type': 'application/json' }, ...options }); const data = await response.json().catch(() => ({})); if (!response.ok) throw Error(data.error || '请求失败，请稍后重试'); return data; };
const formatDate = (value) => value ? new Date(value).toLocaleString('zh-CN') : '—';

export default function Admin() {
  const [booting, setBooting] = useState(true); const [admin, setAdmin] = useState(null); const [page, setPage] = useState('users'); const [turnstile, setTurnstile] = useState({ enabled: false, siteKey: '' }); const [toast, setToast] = useState(null); const [accountOpen, setAccountOpen] = useState(false);
  const notify = useCallback((title, message = '', type = 'info') => setToast({ title, message, type }), []);
  useEffect(() => { Promise.all([api('auth/me'), api('admin/me').catch(() => ({ admin: null }))]).then(([me, session]) => { setTurnstile(me.turnstile || { enabled: false, siteKey: '' }); setAdmin(session.admin || null); }).catch((error) => notify('加载失败', error.message, 'error')).finally(() => setBooting(false)); }, [notify]);
  if (booting) return <LoadingScreen label="正在加载管理后台…" />;
  if (!admin) return <><AdminLogin turnstile={turnstile} done={setAdmin} notify={notify} /><Toast toast={toast} onClose={() => setToast(null)} /></>;
  const logout = async () => { setAccountOpen(false); try { await api('admin/logout', { method: 'POST' }); setAdmin(null); notify('已退出登录', '', 'success'); } catch (error) { notify('退出失败', error.message, 'error'); } };
  return <main className="admin-page"><aside><a href="/admin">LURI ADMIN</a><button className={page === 'users' ? 'active' : ''} onClick={() => setPage('users')}>用户管理</button><button className={page === 'admins' ? 'active' : ''} onClick={() => setPage('admins')}>管理员账号</button><button className={page === 'site' ? 'active' : ''} onClick={() => setPage('site')}>网站设置</button><button className={page === 'email' ? 'active' : ''} onClick={() => setPage('email')}>邮件配置</button></aside><section className="admin-content"><header><span>LURI ADMIN</span><div className="admin-current-account"><button className="admin-account-trigger" type="button" aria-expanded={accountOpen} aria-label={`当前登录账号 ${admin.username}`} onClick={() => setAccountOpen((value) => !value)}>{admin.username}</button>{accountOpen && <><button className="admin-account-backdrop" type="button" aria-label="关闭账号菜单" onClick={() => setAccountOpen(false)} /><section className="admin-account-menu"><button type="button" onClick={() => { setPage('password'); setAccountOpen(false); }}>修改密码</button><button type="button" className="admin-logout" onClick={logout}>退出登录</button></section></>}</div></header>{page === 'users' && <Users notify={notify} />}{page === 'admins' && <AdminAccounts notify={notify} />}{page === 'site' && <SiteConfig notify={notify} />}{page === 'email' && <EmailConfig notify={notify} />}{page === 'password' && <AdminPassword notify={notify} />}</section><Toast toast={toast} onClose={() => setToast(null)} /></main>;
}

function AdminLogin({ turnstile, done, notify }) {
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [token, setToken] = useState(''); const [reset, setReset] = useState(0); const [loading, setLoading] = useState(false);
  useEffect(() => () => document.activeElement?.blur?.(), []);
  const resetTurnstile = useCallback(() => { setToken(''); setReset((value) => value + 1); }, []);
  const submit = async (event) => { event.preventDefault(); if (turnstile.enabled && !token) return notify('请先完成人机验证', '请完成下方的 Turnstile 验证后再尝试', 'error'); setLoading(true); try { const data = await api('admin/login', { method: 'POST', body: JSON.stringify({ username, password, turnstileToken: token }) }); document.activeElement?.blur?.(); notify('登录成功', '', 'success'); done(data.admin); } catch (error) { notify('登录失败', error.message, 'error'); resetTurnstile(); } finally { setLoading(false); } };
  return <main className="admin-login"><form onSubmit={submit}><p>后台管理端</p><h1>LURI ADMIN</h1><label>账号<input value={username} onChange={(event) => setUsername(event.target.value)} autoComplete="username" autoFocus required /></label><PasswordField label="密码" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" required />{turnstile.enabled && <Turnstile siteKey={turnstile.siteKey} onVerify={setToken} onExpire={resetTurnstile} resetSignal={reset} />}<button disabled={loading || (turnstile.enabled && !token)}>{loading ? <><Spinner /> 登录中…</> : '登录'}</button></form></main>;
}

function Generate({ notify }) {
  const [type, setType] = useState('day'); const [value, setValue] = useState(30); const [count, setCount] = useState(1); const [validDays, setValidDays] = useState(30); const [note, setNote] = useState(''); const [codes, setCodes] = useState([]); const [loading, setLoading] = useState(false);
  const unit = type === 'day' ? '天' : type === 'month' ? '个月' : '年'; const presets = type === 'day' ? [7, 30, 90] : type === 'month' ? [1, 3, 6] : [1, 2, 3];
  const changeType = (next) => { setType(next); setValue(next === 'day' ? 30 : 1); };
  const submit = async (event) => { event.preventDefault(); setLoading(true); try { const data = await api('admin/codes', { method: 'POST', body: JSON.stringify({ durationType: type, durationValue: value, count, validDays, note }) }); setCodes(data.codes); notify('生成成功', `已生成 ${data.codes.length} 个兑换码`, 'success'); } catch (error) { notify('生成失败', error.message, 'error'); } finally { setLoading(false); } };
  const copyAll = async () => { try { await navigator.clipboard.writeText(codes.join('\n')); notify('复制成功', '兑换码已全部复制', 'success'); } catch { notify('复制失败', '请检查浏览器剪贴板权限', 'error'); } };
  return <section className="admin-view"><div className="view-heading"><div><span>ACCESS CODES</span><h1>生成兑换码</h1><p>配置网站访问时长与发放数量。</p></div></div><div className="generator-layout"><form className="modern-form" onSubmit={submit}><fieldset><legend>网站访问权限有效期</legend><div className="period-cards">{[['day', '按天'], ['month', '按月'], ['year', '按年']].map(([key, label]) => <button type="button" className={type === key ? 'selected' : ''} onClick={() => changeType(key)} key={key}><b>{label}</b><small>{key === 'day' ? '精确天数' : key === 'month' ? '自然月' : '自然年'}</small></button>)}</div><div className="value-control"><input aria-label="有效期数值" value={value} onChange={(event) => setValue(Math.max(1, Number(event.target.value)))} type="number" min="1" required /><span>{unit}</span></div><div className="quick-values">{presets.map((preset) => <button type="button" className={value === preset ? 'active' : ''} onClick={() => setValue(preset)} key={preset}>{preset}{unit}</button>)}</div></fieldset><div className="form-grid"><label><span>生成数量</span><small>单次最多生成 100 个</small><input value={count} onChange={(event) => setCount(Math.min(100, Math.max(1, Number(event.target.value))))} type="number" min="1" max="100" required /></label><label><span>兑换截止</span><small>到期后可在记录页一键清理</small><div className="suffix-input"><input value={validDays} onChange={(event) => setValidDays(Math.max(1, Number(event.target.value)))} type="number" min="1" required /><i>天</i></div></label></div><label><span>备注</span><small>仅管理员可见，便于区分发放批次</small><input value={note} onChange={(event) => setNote(event.target.value)} maxLength="120" placeholder="例如：九月访问权限活动" /></label><button className="primary generate-button" disabled={loading}>{loading ? <><Spinner /> 正在生成…</> : `生成 ${count} 个兑换码`}</button></form><aside className="generation-summary"><span>生成预览</span><strong>{count}</strong><small>个兑换码</small><dl><dt>单码访问时长</dt><dd>{value} {unit}</dd><dt>兑换期限</dt><dd>{validDays} 天内</dd><dt>状态</dt><dd>生成后立即可用</dd></dl></aside></div>{codes.length > 0 && <GeneratedCodesModal codes={codes} copyAll={copyAll} close={() => setCodes([])} notify={notify} />}</section>;
}

function GeneratedCodesModal({ codes, copyAll, close, notify }) {
  const copyOne = async (code) => { try { await navigator.clipboard.writeText(code); notify('复制成功', code, 'success'); } catch { notify('复制失败', '请检查浏览器剪贴板权限', 'error'); } };
  return <div className="admin-modal" role="dialog" aria-modal="true" aria-label="生成完成"><section><button className="modal-close" onClick={close} aria-label="关闭">×</button><header><span>GENERATED</span><h2>兑换码生成完成</h2><p>共生成 {codes.length} 个兑换码，请妥善保存。</p></header><div className="generated-code-list">{codes.map((code) => <button onClick={() => copyOne(code)} key={code}><code>{code}</code><small>点击复制</small></button>)}</div><footer><button className="copy-all" onClick={copyAll}>一键复制全部</button><button onClick={close}>完成</button></footer></section></div>;
}

function Records({ notify }) {
  const [data, setData] = useState(null); const [status, setStatus] = useState(''); const [email, setEmail] = useState(''); const [page, setPage] = useState(1); const [loading, setLoading] = useState(false); const [confirmId, setConfirmId] = useState(''); const [selected, setSelected] = useState([]); const [bulkConfirm, setBulkConfirm] = useState(false); const [acting, setActing] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { setData(await api(`admin/list?status=${encodeURIComponent(status)}&email=${encodeURIComponent(email)}&page=${page}`)); setSelected([]); setBulkConfirm(false); } catch (error) { notify('记录加载失败', error.message, 'error'); } finally { setLoading(false); } }, [status, email, page, notify]);
  useEffect(() => { load(); }, [load]);
  const copy = async (code) => { if (!code) return notify('无法复制', '历史兑换码未保存明文', 'error'); try { await navigator.clipboard.writeText(code); notify('复制成功', code, 'success'); } catch { notify('复制失败', '请检查浏览器剪贴板权限', 'error'); } };
  const remove = async (id) => { if (confirmId !== id) { setConfirmId(id); return; } setActing(true); try { await api('admin/delete', { method: 'POST', body: JSON.stringify({ id }) }); setConfirmId(''); notify('删除成功', '兑换码及对应访问权限已更新', 'success'); load(); } catch (error) { notify('删除失败', error.message, 'error'); } finally { setActing(false); } };
  const toggleDisabled = async (code) => { setActing(true); try { await api('admin/code-status', { method: 'POST', body: JSON.stringify({ id: code.id, disabled: code.status !== '已禁用' }) }); notify(code.status === '已禁用' ? '启用成功' : '禁用成功', '用户有效期已同步更新', 'success'); load(); } catch (error) { notify('操作失败', error.message, 'error'); } finally { setActing(false); } };
  const bulkDelete = async () => { if (!bulkConfirm) { setBulkConfirm(true); return; } setActing(true); try { const result = await api('admin/bulk-delete', { method: 'POST', body: JSON.stringify({ ids: selected }) }); notify('批量删除完成', `已删除 ${result.deleted} 个兑换码`, 'success'); load(); } catch (error) { notify('批量删除失败', error.message, 'error'); } finally { setActing(false); } };
  const cleanup = async () => { setActing(true); try { const result = await api('admin/cleanup-expired', { method: 'POST', body: '{}' }); notify('清理完成', result.deleted ? `已清理 ${result.deleted} 个过期兑换码` : '没有需要清理的过期兑换码', 'success'); load(); } catch (error) { notify('清理失败', error.message, 'error'); } finally { setActing(false); } };
  const currentIds = data?.items.map((code) => code.id) || []; const allSelected = currentIds.length > 0 && currentIds.every((id) => selected.includes(id));
  const toggleAll = () => setSelected(allSelected ? [] : currentIds); const toggleOne = (id) => setSelected((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]);
  return <section className="admin-view"><div className="view-heading"><div><span>CODE LEDGER</span><h1>兑换码记录</h1><p>所有兑换码均可禁用、启用或删除，网站访问权限会实时同步。</p></div></div><div className="filters"><select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="">全部状态</option><option>未使用</option><option>已使用</option><option>已过期</option><option>已禁用</option></select><input value={email} onChange={(event) => { setEmail(event.target.value); setPage(1); }} placeholder="搜索兑换者邮箱" /><button onClick={load} disabled={loading}>{loading ? <Spinner /> : '查询'}</button></div><div className="record-toolbar"><span>已选择 {selected.length} 项</span><button disabled={!selected.length || acting} className={bulkConfirm ? 'danger' : ''} onClick={bulkDelete}>{bulkConfirm ? '确认批量删除' : '批量删除'}</button><button disabled={acting} onClick={cleanup}>一键清理过期</button></div>{loading && !data ? <div className="admin-inline-loading"><Spinner /><span>加载中…</span></div> : <><div className="record-table"><div className="tr head"><input type="checkbox" checked={allSelected} onChange={toggleAll} aria-label="选择当前页全部兑换码" /><span>兑换码</span><span>访问时长</span><span>状态</span><span>兑换者</span><span>兑换时间</span><span>管理</span></div>{data?.items.length ? data.items.map((code) => <div className="tr" key={code.id}><input type="checkbox" checked={selected.includes(code.id)} onChange={() => toggleOne(code.id)} aria-label={`选择 ${code.code_display}`} /><button className="code-copy" onClick={() => copy(code.code_display)} title="点击复制兑换码"><code>{code.code_display || '历史兑换码'}</code><small>点击复制</small></button><span>{code.durationLabel}</span><b className={`tag ${code.status}`}>{code.status}</b><span>{code.email || '—'}</span><span>{formatDate(code.redeemed_at)}</span><span className="row-actions"><button disabled={acting} onClick={() => toggleDisabled(code)}>{code.status === '已禁用' ? '启用' : '禁用'}</button><button disabled={acting} className={confirmId === code.id ? 'confirm-delete' : ''} onClick={() => remove(code.id)}>{confirmId === code.id ? '确认' : '删除'}</button></span></div>) : <div className="admin-empty">暂无数据</div>}</div><div className="pager"><button disabled={page === 1 || loading} onClick={() => setPage(page - 1)}>上一页</button><span>第 {page} 页 / 共 {Math.max(1, Math.ceil((data?.total || 0) / (data?.size || 20)))} 页</span><button disabled={loading || page * (data?.size || 20) >= (data?.total || 0)} onClick={() => setPage(page + 1)}>下一页</button></div></>}</section>;
}

function Users({ notify }) {
  const [data, setData] = useState(null); const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(1); const [loading, setLoading] = useState(false); const [acting, setActing] = useState(false); const [confirmId, setConfirmId] = useState(''); const [years, setYears] = useState(1); const [cleanupConfirm, setCleanupConfirm] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { setData(await api(`admin/users?query=${encodeURIComponent(query)}&status=${encodeURIComponent(status)}&page=${page}`)); } catch (error) { notify('用户加载失败', error.message, 'error'); } finally { setLoading(false); } }, [query, status, page, notify]);
  useEffect(() => { load(); }, [load]);
  const toggleDisabled = async (user) => { setActing(true); try { await api('admin/user-status', { method: 'POST', body: JSON.stringify({ id: user.id, disabled: user.status !== '已禁用' }) }); notify(user.status === '已禁用' ? '账号已启用' : '账号已禁用', '', 'success'); load(); } catch (error) { notify('操作失败', error.message, 'error'); } finally { setActing(false); } };
  const remove = async (id) => { if (confirmId !== id) { setConfirmId(id); return; } setActing(true); try { await api('admin/user-delete', { method: 'POST', body: JSON.stringify({ id }) }); notify('删除成功', '用户账号及相关兑换码数据已删除', 'success'); setConfirmId(''); load(); } catch (error) { notify('删除失败', error.message, 'error'); } finally { setActing(false); } };
  const cleanup = async () => { if (!cleanupConfirm) { setCleanupConfirm(true); return; } setActing(true); try { const result = await api('admin/users-cleanup', { method: 'POST', body: JSON.stringify({ years }) }); notify('清理完成', `已删除 ${result.deleted} 个长期未登录用户`, 'success'); setCleanupConfirm(false); load(); } catch (error) { notify('清理失败', error.message, 'error'); } finally { setActing(false); } };
  return <section className="admin-view"><div className="view-heading"><div><span>USER ACCOUNTS</span><h1>用户管理</h1><p>管理用户状态、登录记录和 Provider 配置概况。</p></div></div><div className="user-cleanup"><div><b>清理长期未登录用户</b><small>同时删除相关账号、会话和已保存的 Provider 配置</small></div><label><input type="number" min="1" max="100" value={years} onChange={(event) => { setYears(Math.max(1, Number(event.target.value))); setCleanupConfirm(false); }} /><span>年未登录</span></label><button className={cleanupConfirm ? 'danger' : ''} onClick={cleanup} disabled={acting}>{cleanupConfirm ? `确认清理 ${years} 年未登录用户` : '开始清理'}</button></div><div className="filters"><select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="">全部状态</option><option value="active">正常</option><option value="disabled">已禁用</option></select><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="搜索名称或邮箱" /><button onClick={load} disabled={loading}>{loading ? <Spinner /> : '查询'}</button></div>{loading && !data ? <div className="admin-inline-loading"><Spinner />加载中…</div> : <><div className="user-table"><div className="user-row head"><span>用户</span><span>状态</span><span>最后登录</span><span>注册时间</span><span>Provider</span><span>管理</span></div>{data?.items.length ? data.items.map((user) => <div className="user-row" key={user.id}><span className="user-identity"><b>{user.display_name}</b><small>{user.email}</small></span><b className={`tag ${user.status}`}>{user.status}</b><span>{formatDate(user.last_login_at)}</span><span>{formatDate(user.created_at)}</span><span className="user-identity"><b>{user.provider_count} 个</b><small>{user.active_provider || '未激活'}</small></span><span className="row-actions"><button disabled={acting} onClick={() => toggleDisabled(user)}>{user.status === '已禁用' ? '启用' : '禁用'}</button><button disabled={acting} className={confirmId === user.id ? 'confirm-delete' : ''} onClick={() => remove(user.id)}>{confirmId === user.id ? '确认' : '删除'}</button></span></div>) : <div className="admin-empty">暂无用户</div>}</div><div className="pager"><button disabled={page === 1 || loading} onClick={() => setPage(page - 1)}>上一页</button><span>第 {page} 页 / 共 {Math.max(1, Math.ceil((data?.total || 0) / (data?.size || 20)))} 页</span><button disabled={loading || page * (data?.size || 20) >= (data?.total || 0)} onClick={() => setPage(page + 1)}>下一页</button></div></>}</section>;
}

function AdminAccounts({ notify }) {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [creating, setCreating] = useState(false); const [confirmId, setConfirmId] = useState(''); const [editing, setEditing] = useState(null);
  const load = useCallback(async () => { try { setData(await api('admin/accounts')); } catch (error) { notify('管理员账号加载失败', error.message, 'error'); } finally { setLoading(false); } }, [notify]);
  useEffect(() => { load(); }, [load]);
  const create = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (form.get('password') !== form.get('confirm')) return notify('添加失败', '两次输入的密码不一致', 'error'); setCreating(true); try { await api('admin/accounts', { method: 'POST', body: JSON.stringify({ username: form.get('username'), password: form.get('password') }) }); event.currentTarget.reset(); notify('添加成功', '新管理员账号已创建', 'success'); load(); } catch (error) { notify('添加失败', error.message, 'error'); } finally { setCreating(false); } };
  const remove = async (id) => { if (confirmId !== id) { setConfirmId(id); return; } try { await api('admin/account-delete', { method: 'POST', body: JSON.stringify({ id }) }); notify('删除成功', '', 'success'); setConfirmId(''); load(); } catch (error) { notify('删除失败', error.message, 'error'); } };
  return <section className="admin-view"><div className="view-heading"><div><span>ADMIN ACCOUNTS</span><h1>管理员账号</h1><p>添加管理员、重置密码或移除不再使用的账号。</p></div></div><div className="admin-account-layout"><form className="admin-form" onSubmit={create}><h3>添加管理员</h3><label>管理员账号<input name="username" minLength="3" maxLength="32" pattern="[A-Za-z0-9_.-]+" autoComplete="off" required /></label><PasswordField label="密码" name="password" minLength="8" autoComplete="new-password" required /><PasswordField label="确认密码" name="confirm" minLength="8" autoComplete="new-password" required /><button className="primary" disabled={creating}>{creating ? <><Spinner /> 添加中…</> : '添加管理员'}</button></form><div className="admin-account-list">{loading ? <div className="admin-inline-loading"><Spinner />加载中…</div> : data?.items.map((account) => <div key={account.id}><span><b>{account.username}</b><small>{account.id === data.currentId ? '当前登录账号' : `创建于 ${formatDate(account.created_at)}`}</small></span><span className="row-actions"><button onClick={() => setEditing(account)}>修改密码</button><button disabled={account.id === data.currentId} className={confirmId === account.id ? 'confirm-delete' : ''} onClick={() => remove(account.id)}>{confirmId === account.id ? '确认删除' : '删除'}</button></span></div>)}</div></div>{editing && <AdminAccountPassword account={editing} close={() => setEditing(null)} notify={notify} />}</section>;
}

function AdminAccountPassword({ account, close, notify }) {
  const [loading, setLoading] = useState(false); const submit = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (form.get('password') !== form.get('confirm')) return notify('修改失败', '两次输入的密码不一致', 'error'); setLoading(true); try { await api('admin/account-password', { method: 'POST', body: JSON.stringify({ id: account.id, password: form.get('password') }) }); notify('修改成功', `${account.username} 的密码已更新`, 'success'); close(); } catch (error) { notify('修改失败', error.message, 'error'); } finally { setLoading(false); } };
  return <div className="admin-modal" role="dialog" aria-modal="true" aria-label="修改管理员密码"><section className="small-modal"><button className="modal-close" onClick={close}>×</button><header><span>RESET PASSWORD</span><h2>修改 {account.username} 的密码</h2></header><form className="admin-form" onSubmit={submit}><PasswordField label="新密码" name="password" minLength="8" autoComplete="new-password" required /><PasswordField label="确认密码" name="confirm" minLength="8" autoComplete="new-password" required /><button className="primary" disabled={loading}>{loading ? <><Spinner /> 保存中…</> : '保存新密码'}</button></form></section></div>;
}

function AdminPassword({ notify }) {
  const [loading, setLoading] = useState(false);
  const submit = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (form.get('next') !== form.get('confirm')) return notify('无法修改密码', '两次输入的新密码不一致', 'error'); setLoading(true); try { await api('admin/password', { method: 'POST', body: JSON.stringify({ currentPassword: form.get('current'), newPassword: form.get('next') }) }); event.currentTarget.reset(); notify('修改成功', '管理员密码已更新', 'success'); } catch (error) { notify('修改失败', error.message, 'error'); } finally { setLoading(false); } };
  return <section><div className="view-heading"><div><span>SECURITY</span><h1>修改密码</h1><p>定期更新管理员密码，保障后台安全。</p></div></div><form className="admin-form" onSubmit={submit}><PasswordField label="当前密码" name="current" autoComplete="current-password" required /><PasswordField label="新密码" name="next" minLength="8" autoComplete="new-password" required /><PasswordField label="确认新密码" name="confirm" minLength="8" autoComplete="new-password" required /><button className="primary" disabled={loading}>{loading ? <><Spinner /> 保存中…</> : '保存修改'}</button></form></section>;
}

function SettingSwitch({ checked, saving, disabled = false, onClick }) { return <button type="button" role="switch" aria-checked={checked} aria-busy={saving} aria-label={saving ? '保存中' : checked ? '关闭此设置' : '开启此设置'} className={`admin-switch${checked ? ' active' : ''}`} onClick={onClick} disabled={saving || disabled}><i /></button>; }

function SettingCard({ title, description, checked, saving, disabled = false, onClick }) {
  return <div className={`site-settings-card${disabled ? ' disabled' : ''}`}><div><strong>{title}</strong><p>{description}</p></div><SettingSwitch checked={checked} saving={saving} disabled={disabled} onClick={onClick} /></div>;
}

function SiteConfig({ notify }) {
  const initial = { blog: true, posts: true, about: true, music: true, musicInBlogNav: true, blogNavInMusic: true, docs: true, required: true };
  const [config, setConfig] = useState(initial); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const fromResponse = (data) => ({ blog: data.blogSiteEnabled !== false, posts: data.blogPostsEnabled !== false, about: data.aboutPageEnabled !== false, music: data.musicPageEnabled !== false, musicInBlogNav: data.musicNavigationEnabled !== false, blogNavInMusic: data.musicBlogNavigationEnabled !== false, docs: data.docsPageEnabled !== false, required: data.musicAccessRequired !== false });
  useEffect(() => { api('admin/site-config').then((data) => setConfig(fromResponse(data))).catch((error) => notify('网站设置加载失败', error.message, 'error')).finally(() => setLoading(false)); }, [notify]);
  const save = async (next) => { const previous = config; setConfig(next); setSaving(true); try { const data = await api('admin/site-config', { method: 'POST', body: JSON.stringify({ blogSiteEnabled: next.blog, blogPostsEnabled: next.posts, aboutPageEnabled: next.about, musicPageEnabled: next.music, musicNavigationEnabled: next.musicInBlogNav, musicBlogNavigationEnabled: next.blogNavInMusic, docsPageEnabled: next.docs, musicAccessRequired: next.required }) }); setConfig(fromResponse(data)); notify('设置已保存', '', 'success'); } catch (error) { setConfig(previous); notify('保存失败', error.message, 'error'); } finally { setSaving(false); } };
  const toggle = (key) => save({ ...config, [key]: !config[key] });
  return <section className="admin-view"><div className="view-heading"><div><span>SITE SETTINGS</span><h1>网站设置</h1><p>管理博客、LURI MUSIC 和导航开关。</p></div></div>{loading ? <div className="admin-inline-loading"><Spinner /><span>加载中…</span></div> : <div className="site-settings-list"><section className="site-settings-group"><header><span>PERSONAL BLOG</span><h2>个人博客</h2></header><div className="site-settings-grid"><SettingCard title="博客站点" description="博客首页和子页面" checked={config.blog} saving={saving} onClick={() => toggle('blog')} /><SettingCard title="随笔菜单与导航" description="随笔导航、列表和详情页" checked={config.posts} saving={saving} disabled={!config.blog} onClick={() => toggle('posts')} /><SettingCard title="关于我菜单与导航" description="关于导航和页面" checked={config.about} saving={saving} disabled={!config.blog} onClick={() => toggle('about')} /><SettingCard title="MUSIC 菜单" description="博客一级导航中的 MUSIC 入口" checked={config.musicInBlogNav} saving={saving} disabled={!config.blog || !config.music} onClick={() => toggle('musicInBlogNav')} /></div></section><section className="site-settings-group"><header><span>LURI MUSIC</span><h2>LURI MUSIC</h2></header><div className="site-settings-grid"><SettingCard title="LURI MUSIC 站点" description="LURI MUSIC 站点访问" checked={config.music} saving={saving} onClick={() => toggle('music')} /><SettingCard title="博客菜单" description="音乐页的博客一级导航" checked={config.blogNavInMusic} saving={saving} disabled={!config.music || !config.blog} onClick={() => toggle('blogNavInMusic')} /><SettingCard title="开发者文档" description="文档入口和 /docs 页面" checked={config.docs} saving={saving} onClick={() => toggle('docs')} /><SettingCard title="用户登录功能" description="用户登录和音乐访问权限" checked={config.required} saving={saving} disabled={!config.music} onClick={() => toggle('required')} /></div></section></div>}</section>;
}

function EmailConfig({ notify }) {
  const [config, setConfig] = useState(null); const [apiKey, setApiKey] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  useEffect(() => { api('admin/email-config').then((data) => { setConfig(data); setApiKey(data.apiKey || ''); }).catch((error) => notify('邮件配置加载失败', error.message, 'error')).finally(() => setLoading(false)); }, [notify]);
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { const data = await api('admin/email-config', { method: 'POST', body: JSON.stringify({ apiKey }) }); setConfig({ ...data, apiKey }); notify('保存成功', 'Resend 邮件服务配置已更新', 'success'); } catch (error) { notify('保存失败', error.message, 'error'); } finally { setSaving(false); } };
  return <section className="admin-view"><div className="view-heading"><div><span>EMAIL DELIVERY</span><h1>邮件配置</h1><p>用于用户注册验证和忘记密码验证码邮件。</p></div></div>{loading ? <div className="admin-inline-loading"><Spinner /><span>加载中…</span></div> : <form className="admin-form email-config-form" onSubmit={submit}><div className={`config-status ${config?.configured ? 'ready' : ''}`}><span>{config?.configured ? '已配置' : '未配置'}</span><small>{config?.source === 'database' ? '后台配置' : config?.source === 'environment' ? '环境变量配置' : '暂无可用密钥'}</small></div><label>发件邮箱<input value={config?.sender || 'no-reply@luri.cc.cd'} readOnly /></label><PasswordField label="Resend API Key" value={apiKey} onChange={(event) => setApiKey(event.target.value)} autoComplete="off" required /><p className="field-help">密钥仅对已登录管理员回显，默认以密文显示。保存后优先使用后台配置。</p><button className="primary" disabled={saving}>{saving ? <><Spinner /> 保存中…</> : '保存邮件配置'}</button></form>}</section>;
}

function PasswordField({ label, ...props }) {
  const [visible, setVisible] = useState(false);
  return <label>{label}<span className="password-input"><input {...props} type={visible ? 'text' : 'password'} /><button type="button" onClick={() => setVisible((value) => !value)} aria-label={visible ? '隐藏内容' : '显示内容'} title={visible ? '隐藏' : '显示'}><EyeIcon crossed={!visible} /></button></span></label>;
}

function EyeIcon({ crossed = false }) { return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z" /><circle cx="12" cy="12" r="2.7" />{crossed && <path d="m4 4 16 16" />}</svg>; }
