import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SONG_LIMIT = 1000;
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const NETEASE_TOPLIST_URL = 'https://music.163.com/api/toplist/detail';
const NETEASE_PLAYLIST_URL = 'https://music.163.com/api/v6/playlist/detail';
const QQ_API_URL = 'https://u.y.qq.com/cgi-bin/musicu.fcg';
const GENERATED_AT = new Date().toISOString();

const headers = (referer) => ({
  accept: 'application/json, text/plain, */*',
  referer,
  'user-agent': 'Mozilla/5.0 (compatible; LuriSingerPool/1.0)',
});

async function getJson(url, referer, attempts = 3) {
  let lastError;
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      const response = await fetch(url, { headers: headers(referer) });
      if (!response.ok) throw new Error(`HTTP ${response.status} ${response.statusText}`);
      return await response.json();
    } catch (error) {
      lastError = error;
      if (attempt < attempts) await new Promise((done) => setTimeout(done, attempt * 500));
    }
  }
  throw lastError;
}

function qqUrl(requests) {
  const data = { comm: { cv: 1602, ct: 20 }, ...requests };
  const url = new URL(QQ_API_URL);
  url.searchParams.set('data', JSON.stringify(data));
  return url;
}

export function normalizeSingerName(value) {
  return String(value || '')
    .normalize('NFKC')
    .replace(/[\u200B-\u200D\u2060\uFEFF]/gu, '')
    .trim()
    .replace(/\s+/gu, ' ')
    .toLocaleLowerCase();
}

function addUniqueSongs(target, seen, songs, songId, artists, chart, limit = SONG_LIMIT) {
  let added = 0;
  for (const song of songs) {
    if (target.length >= limit) break;
    const id = songId(song);
    if (id === undefined || id === null || id === '' || seen.has(String(id))) continue;
    seen.add(String(id));
    target.push({ id: String(id), artists: artists(song) });
    added += 1;
  }
  if (added) chart.uniqueSongsUsed = added;
}

async function fetchNeteaseSongs() {
  const catalog = await getJson(NETEASE_TOPLIST_URL, 'https://music.163.com/');
  const songs = [];
  const seen = new Set();
  const charts = [];

  for (const item of catalog.list || []) {
    if (songs.length >= SONG_LIMIT) break;
    const url = new URL(NETEASE_PLAYLIST_URL);
    url.searchParams.set('id', item.id);
    url.searchParams.set('n', Math.max(Number(item.trackCount) || 1000, 1000));
    const payload = await getJson(url, 'https://music.163.com/');
    const tracks = payload.playlist?.tracks || [];
    const chart = { id: String(item.id), name: item.name, fetchedSongs: tracks.length };
    addUniqueSongs(songs, seen, tracks, (track) => track.id, (track) => track.ar || [], chart);
    charts.push(chart);
  }

  if (songs.length < SONG_LIMIT) throw new Error(`网易榜单仅抓到 ${songs.length} 首去重歌曲`);
  return { songs, charts };
}

async function fetchQqSongs() {
  const catalog = await getJson(qqUrl({
    toplist: { module: 'musicToplist.ToplistInfoServer', method: 'GetAll', param: {} },
  }), 'https://y.qq.com/');
  const toplists = (catalog.toplist?.data?.group || []).flatMap((group) => group.toplist || []);
  const songs = [];
  const seen = new Set();
  const charts = [];

  for (const item of toplists) {
    if (songs.length >= SONG_LIMIT) break;
    const requested = Math.max(Number(item.totalNum) || 100, 100);
    const payload = await getJson(qqUrl({
      detail: {
        module: 'musicToplist.ToplistInfoServer',
        method: 'GetDetail',
        param: { topId: item.topId, offset: 0, num: requested, period: item.period || '' },
      },
    }), 'https://y.qq.com/');
    const tracks = payload.detail?.data?.songInfoList || [];
    const chart = { id: String(item.topId), name: item.title, fetchedSongs: tracks.length };
    addUniqueSongs(songs, seen, tracks, (track) => track.mid || track.id, (track) => track.singer || [], chart);
    charts.push(chart);
  }

  if (songs.length < SONG_LIMIT) throw new Error(`QQ 音乐榜单仅抓到 ${songs.length} 首去重歌曲`);
  return { songs, charts };
}

function collectSingers(songs) {
  const singers = new Map();
  for (const song of songs) {
    for (const artist of song.artists) {
      const name = String(artist?.name || '').normalize('NFKC').trim().replace(/\s+/gu, ' ');
      const key = normalizeSingerName(name);
      if (key && !singers.has(key)) singers.set(key, name);
    }
  }
  return singers;
}

function formatSingerModule(singers, stats) {
  const names = [...singers.values()].sort((left, right) => left.localeCompare(right, 'zh-Hans-CN', { sensitivity: 'base' }));
  const rows = names.map((name) => `  ${JSON.stringify(name)},`).join('\n');
  return `// Generated by npm run update:singers at ${GENERATED_AT}.
// Songs: NetEase ${stats.neteaseSongs}, QQ Music ${stats.qqSongs}; normalized singers: ${stats.mergedSingers}.
export const SINGERS = [
${rows}
];
`;
}

function chartTable(charts) {
  return charts.map((chart) => `| ${chart.id} | ${String(chart.name).replaceAll('|', '\\|')} | ${chart.fetchedSongs} | ${chart.uniqueSongsUsed || 0} |`).join('\n');
}

function formatReport(netease, qq, stats) {
  return `# 本地歌手池抓取统计

- 抓取时间（UTC）：${GENERATED_AT}
- 网易榜单歌曲：${stats.neteaseSongs} 首；标准化去重歌手：${stats.neteaseSingers} 名
- QQ 音乐榜单歌曲：${stats.qqSongs} 首；标准化去重歌手：${stats.qqSingers} 名
- 两平台合并：${stats.mergedSingers} 名（重合 ${stats.overlapSingers} 名）

口径：按平台官方榜单目录顺序抓取，歌曲 ID 去重后各取前 ${SONG_LIMIT} 首。歌手名经过 Unicode NFKC、移除零宽字符、去除首尾空白、连续空白合并为一个空格、转小写生成去重键；歌手池展示名保留接口中的首个标准化原文。

## 网易榜单

数据源：\`${NETEASE_TOPLIST_URL}\` 及榜单详情接口。

| 榜单 ID | 榜单 | 接口返回歌曲 | 纳入的去重歌曲 |
| --- | --- | ---: | ---: |
${chartTable(netease.charts)}

## QQ 音乐榜单

数据源：\`${QQ_API_URL}\` 的 \`GetAll\` 与 \`GetDetail\`。

| 榜单 ID | 榜单 | 接口返回歌曲 | 纳入的去重歌曲 |
| --- | --- | ---: | ---: |
${chartTable(qq.charts)}
`;
}

async function main() {
  const [netease, qq] = await Promise.all([fetchNeteaseSongs(), fetchQqSongs()]);
  const neteaseSingers = collectSingers(netease.songs);
  const qqSingers = collectSingers(qq.songs);
  const merged = new Map(neteaseSingers);
  for (const [key, name] of qqSingers) if (!merged.has(key)) merged.set(key, name);
  const overlap = [...neteaseSingers.keys()].filter((key) => qqSingers.has(key)).length;
  const stats = {
    neteaseSongs: netease.songs.length,
    qqSongs: qq.songs.length,
    neteaseSingers: neteaseSingers.size,
    qqSingers: qqSingers.size,
    overlapSingers: overlap,
    mergedSingers: merged.size,
  };

  const singerPath = resolve(ROOT, 'src/data/singers.js');
  const reportPath = resolve(ROOT, 'docs/singer-pool-stats.md');
  await mkdir(dirname(singerPath), { recursive: true });
  await writeFile(singerPath, formatSingerModule(merged, stats), 'utf8');
  await writeFile(reportPath, formatReport(netease, qq, stats), 'utf8');
  console.log(JSON.stringify(stats, null, 2));
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
