import { cookie, hash, id, json, now, passwordHash, sessionCookie, token, verifyPassword, verifyTurnstileToken } from './shared.js';
const UC='luri_music_session',AC='luri_music_admin',body=async r=>r.json().catch(()=>({})),email=v=>String(v||'').trim().toLowerCase(),valid=v=>typeof v==='string'&&v.length>=8&&v.length<=128;
const user=async(r,e)=>{const v=cookie(r,UC);return v&&e.LURI_MUSIC_DB.prepare('SELECT u.id,u.email,u.display_name,e.expires_at FROM luri_music_sessions s JOIN luri_music_users u ON u.id=s.user_id LEFT JOIN luri_music_entitlements e ON e.user_id=u.id WHERE s.token_hash=? AND s.expires_at>?').bind(await hash(v),now()).first()};
const pub=u=>u&&({id:u.id,email:u.email,name:u.display_name,expiresAt:u.expires_at||null,hasPlayback:!!(u.expires_at&&Date.parse(u.expires_at)>Date.now())});
const admin=async(r,e)=>{const v=cookie(r,AC);return !!(v&&await e.LURI_MUSIC_DB.prepare('SELECT id FROM luri_music_admin_sessions WHERE token_hash=? AND expires_at>?').bind(await hash(v),now()).first())};
const session=async(uid,e)=>{const v=token();await e.LURI_MUSIC_DB.prepare('INSERT INTO luri_music_sessions(id,user_id,token_hash,expires_at,created_at) VALUES(?,?,?,?,?)').bind(id(),uid,await hash(v),new Date(Date.now()+2592e6).toISOString(),now()).run();return v};
const expiry=(base,type,n)=>{const d=new Date(base),t=new Date(d);if(type==='day')return new Date(d.getTime()+n*864e5).toISOString();if(type==='month')t.setMonth(t.getMonth()+n);else t.setFullYear(t.getFullYear()+n);if(t.getDate()!==d.getDate())t.setDate(0);return t.toISOString()};
const label=c=>`${c.duration_value}${c.duration_type==='day'?'天':c.duration_type==='month'?'个月':'年'}`,status=c=>c.disabled_at?'已作废':c.redeemed_at?'已使用':Date.parse(c.expires_at)<=Date.now()?'已过期':'未使用';export async function hasMusicAccess(r,e){return !!pub(await user(r,e))?.hasPlayback}
const verifyHuman=async(data,env)=>{const result=await verifyTurnstileToken(data.turnstileToken,env);return result.success?null:json({error:result.reason==='missing-token'?'请先完成人机验证':'人机验证未通过'},400)};
export async function handleLuriMusic(r,e){if(!e.LURI_MUSIC_DB)return json({error:'音乐服务尚未配置'},503);const a=new URL(r.url).pathname.replace('/api/luri-music/','');
if(a==='auth/me')return json({user:pub(await user(r,e)),turnstile:{enabled:Boolean(e.TURNSTILE_SITE_KEY&&e.TURNSTILE_SECRET_KEY),siteKey:e.TURNSTILE_SITE_KEY||''}});
if(a==='auth/register'&&r.method==='POST'){const d=await body(r),mail=email(d.email),name=String(d.name||'').trim().slice(0,40);if(!/^\S+@\S+\.\S+$/.test(mail)||!name||!valid(d.password))return json({error:'请填写名称、有效邮箱和至少 8 位密码'},400);const human=await verifyHuman(d,e);if(human)return human;const uid=id();try{await e.LURI_MUSIC_DB.prepare('INSERT INTO luri_music_users(id,email,display_name,password_hash,created_at,updated_at) VALUES(?,?,?,?,?,?)').bind(uid,mail,name,await passwordHash(d.password),now(),now()).run()}catch{return json({error:'该邮箱已注册'},409)}const v=await session(uid,e);return json({user:{id:uid,email:mail,name,expiresAt:null,hasPlayback:false}},201,{'set-cookie':sessionCookie(UC,v,2592000)})}
if(a==='auth/login'&&r.method==='POST'){const d=await body(r),human=await verifyHuman(d,e);if(human)return human;const u=await e.LURI_MUSIC_DB.prepare('SELECT * FROM luri_music_users WHERE email=?').bind(email(d.email)).first();if(!u||!await verifyPassword(d.password||'',u.password_hash))return json({error:'邮箱或密码错误'},401);const ent=await e.LURI_MUSIC_DB.prepare('SELECT expires_at FROM luri_music_entitlements WHERE user_id=?').bind(u.id).first(),v=await session(u.id,e);return json({user:pub({...u,expires_at:ent?.expires_at})},200,{'set-cookie':sessionCookie(UC,v,2592000)})}
if(a==='auth/logout')return json({ok:true},200,{'set-cookie':sessionCookie(UC,'',0)});
if(a==='admin/logout')return json({ok:true},200,{'set-cookie':sessionCookie(AC,'',0)});
if(a==='auth/password'&&r.method==='POST'){const u=await user(r,e),d=await body(r);if(!u)return json({error:'请先登录'},401);const row=await e.LURI_MUSIC_DB.prepare('SELECT password_hash FROM luri_music_users WHERE id=?').bind(u.id).first();if(!await verifyPassword(d.currentPassword||'',row.password_hash))return json({error:'旧密码错误'},400);if(!valid(d.password))return json({error:'新密码至少需要 8 位'},400);await e.LURI_MUSIC_DB.prepare('UPDATE luri_music_users SET password_hash=?,updated_at=? WHERE id=?').bind(await passwordHash(d.password),now(),u.id).run();return json({ok:true})}
if(a==='redeem'&&r.method==='POST'){const u=await user(r,e),d=await body(r);if(!u)return json({error:'请先登录'},401);const human=await verifyHuman(d,e);if(human)return human;const code=String(d.code||'').replace(/[^a-z0-9]/ig,'').toUpperCase(),c=await e.LURI_MUSIC_DB.prepare('SELECT * FROM luri_music_codes WHERE code_hash=?').bind(await hash(code)).first();if(!c)return json({error:'兑换码不存在'},400);if(c.disabled_at)return json({error:'兑换码已作废'},400);if(c.redeemed_at)return json({error:'兑换码已使用'},400);if(Date.parse(c.expires_at)<=Date.now())return json({error:'兑换码已过期'},400);const old=await e.LURI_MUSIC_DB.prepare('SELECT expires_at FROM luri_music_entitlements WHERE user_id=?').bind(u.id).first(),ex=expiry(Math.max(Date.now(),Date.parse(old?.expires_at||0)),c.duration_type,c.duration_value);await e.LURI_MUSIC_DB.batch([e.LURI_MUSIC_DB.prepare('UPDATE luri_music_codes SET redeemed_by=?,redeemed_at=? WHERE id=? AND redeemed_at IS NULL').bind(u.id,now(),c.id),e.LURI_MUSIC_DB.prepare('INSERT INTO luri_music_entitlements(user_id,expires_at,updated_at) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET expires_at=excluded.expires_at,updated_at=excluded.updated_at').bind(u.id,ex,now())]);return json({expiresAt:ex})}
if(a==='admin/login'&&r.method==='POST'){const d=await body(r),human=await verifyHuman(d,e);if(human)return human;const cr=await e.LURI_MUSIC_DB.prepare('SELECT password_hash FROM luri_music_admin_credentials WHERE id=1').first(),ok=cr?await verifyPassword(d.password||'',cr.password_hash):!!(e.ADMIN_PASSWORD&&d.password===e.ADMIN_PASSWORD);if(!ok)return json({error:'账号或密码错误'},401);const v=token();await e.LURI_MUSIC_DB.prepare('INSERT INTO luri_music_admin_sessions(id,token_hash,expires_at,created_at) VALUES(?,?,?,?)').bind(id(),await hash(v),new Date(Date.now()+288e5).toISOString(),now()).run();return json({ok:true},200,{'set-cookie':sessionCookie(AC,v,28800)})}
if(!await admin(r,e))return json({error:'管理员登录已失效'},401);
if(a==='admin/codes'&&r.method==='POST'){const d=await body(r),type=['day','month','year'].includes(d.durationType)?d.durationType:'day',value=Math.min(100,Math.max(1,Number(d.durationValue)||0)),count=Math.min(100,Math.max(1,Number(d.count)||1)),validDays=Math.min(3650,Math.max(1,Number(d.validDays)||30));if(!value)return json({error:'有效期数值不正确'},400);const codes=[];for(let i=0;i<count;i++){const raw=[...crypto.getRandomValues(new Uint8Array(10))].map(x=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[x%32]).join(''),code=`LM-${raw.slice(0,5)}-${raw.slice(5)}`;codes.push(code);await e.LURI_MUSIC_DB.prepare('INSERT INTO luri_music_codes(id,code_hash,code_display,duration_days,duration_type,duration_value,expires_at,note,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(id(),await hash(code.replaceAll('-','')),code,value,type,value,new Date(Date.now()+validDays*864e5).toISOString(),String(d.note||'').slice(0,120),now()).run()}return json({codes})}
if(a==='admin/list'&&r.method==='GET'){const u=new URL(r.url),kind=u.searchParams.get('kind')||'all',s=u.searchParams.get('status')||'',q=u.searchParams.get('email')||'',page=Math.max(1,Number(u.searchParams.get('page'))||1),size=20,w=[kind==='redeemed'?'c.redeemed_at IS NOT NULL':'1=1'],args=[];if(s){w.push("CASE WHEN c.disabled_at IS NOT NULL THEN '已作废' WHEN c.redeemed_at IS NOT NULL THEN '已使用' WHEN c.expires_at<=? THEN '已过期' ELSE '未使用' END=?");args.push(now(),s)}if(q){w.push('u.email LIKE ?');args.push(`%${q}%`)}const from=` FROM luri_music_codes c LEFT JOIN luri_music_users u ON u.id=c.redeemed_by LEFT JOIN luri_music_entitlements ent ON ent.user_id=c.redeemed_by WHERE ${w.join(' AND ')}`,total=await e.LURI_MUSIC_DB.prepare(`SELECT count(*) n${from}`).bind(...args).first(),rows=await e.LURI_MUSIC_DB.prepare(`SELECT c.*,u.email,ent.expires_at member_expires_at${from} ORDER BY c.created_at DESC LIMIT ? OFFSET ?`).bind(...args,size,(page-1)*size).all();return json({items:rows.results.map(c=>({...c,status:status(c),durationLabel:label(c),membershipStatus:c.member_expires_at&&Date.parse(c.member_expires_at)>Date.now()?'有效':'已过期'})),total:total.n,page,size})}
if(a==='admin/revoke'&&r.method==='POST'){const d=await body(r),x=await e.LURI_MUSIC_DB.prepare('UPDATE luri_music_codes SET disabled_at=? WHERE id=? AND redeemed_at IS NULL AND disabled_at IS NULL').bind(now(),d.id).run();return x.meta.changes?json({ok:true}):json({error:'仅可作废未使用兑换码'},400)}
if(a==='admin/password'&&r.method==='POST'){const d=await body(r),cr=await e.LURI_MUSIC_DB.prepare('SELECT password_hash FROM luri_music_admin_credentials WHERE id=1').first(),ok=cr?await verifyPassword(d.currentPassword||'',cr.password_hash):!!(e.ADMIN_PASSWORD&&d.currentPassword===e.ADMIN_PASSWORD);if(!ok)return json({error:'当前密码错误'},400);if(!valid(d.newPassword))return json({error:'新密码至少需要 8 位'},400);const h=await passwordHash(d.newPassword);if(cr)await e.LURI_MUSIC_DB.prepare('UPDATE luri_music_admin_credentials SET password_hash=?,updated_at=? WHERE id=1').bind(h,now()).run();else await e.LURI_MUSIC_DB.prepare('INSERT INTO luri_music_admin_credentials(id,password_hash,updated_at) VALUES(1,?,?)').bind(h,now()).run();return json({ok:true})}return json({error:'Not found'},404)}
