import { cookie, hash, id, json, now, passwordHash, sessionCookie, token, verifyPassword, verifyTurnstile } from './shared.js';

const USER_COOKIE = 'luri_music_session'; const ADMIN_COOKIE = 'luri_music_admin';
const body = async (request) => { try { return await request.json(); } catch { return {}; } };
const cleanEmail = (value) => String(value || '').trim().toLowerCase();
const validPassword = (value) => typeof value === 'string' && value.length >= 8 && value.length <= 128;
const userSession = async (request, env) => {
  const value = cookie(request, USER_COOKIE); if (!value || !env.LURI_MUSIC_DB) return null;
  return env.LURI_MUSIC_DB.prepare('SELECT u.id, u.email, u.display_name, e.expires_at FROM luri_music_sessions s JOIN luri_music_users u ON u.id=s.user_id LEFT JOIN luri_music_entitlements e ON e.user_id=u.id WHERE s.token_hash=? AND s.expires_at>?').bind(await hash(value), now()).first();
};
const adminSession = async (request, env) => {
  const value = cookie(request, ADMIN_COOKIE); if (!value || !env.LURI_MUSIC_DB) return false;
  return Boolean(await env.LURI_MUSIC_DB.prepare('SELECT id FROM luri_music_admin_sessions WHERE token_hash=? AND expires_at>?').bind(await hash(value), now()).first());
};
const requireDb = (env) => env.LURI_MUSIC_DB ? null : json({ error: 'Luri Music is not configured' }, 503);
const requireUser = async (request, env) => { const user = await userSession(request, env); return user || null; };
const createUserSession = async (userId, env) => { const value = token(); const expires = new Date(Date.now() + 30 * 864e5).toISOString(); await env.LURI_MUSIC_DB.prepare('INSERT INTO luri_music_sessions(id,user_id,token_hash,expires_at,created_at) VALUES(?,?,?,?,?)').bind(id(), userId, await hash(value), expires, now()).run(); return value; };
const publicUser = (user) => user && ({ id: user.id, email: user.email, name: user.display_name, expiresAt: user.expires_at || null, hasPlayback: Boolean(user.expires_at && Date.parse(user.expires_at) > Date.now()) });

export async function handleLuriMusic(request, env) {
  const unavailable = requireDb(env); if (unavailable) return unavailable;
  const { pathname } = new URL(request.url); const action = pathname.replace('/api/luri-music/', '');
  if (action === 'auth/me' && request.method === 'GET') return json({ user: publicUser(await userSession(request, env)), turnstileSiteKey: env.TURNSTILE_SITE_KEY || '' });
  if (action === 'auth/register' && request.method === 'POST') {
    const data = await body(request); const email = cleanEmail(data.email); const name = String(data.name || '').trim().slice(0, 40);
    if (!/^\S+@\S+\.\S+$/.test(email) || !name || !validPassword(data.password)) return json({ error: '请填写昵称、有效邮箱和至少 8 位密码' }, 400);
    if (!(await verifyTurnstile(data.turnstileToken, env, request))) return json({ error: '人机验证未通过' }, 403);
    const userId = id(); try { await env.LURI_MUSIC_DB.prepare('INSERT INTO luri_music_users(id,email,display_name,password_hash,created_at,updated_at) VALUES(?,?,?,?,?,?)').bind(userId, email, name, await passwordHash(data.password), now(), now()).run(); } catch { return json({ error: '该邮箱已注册' }, 409); }
    const value = await createUserSession(userId, env); return json({ user: { id: userId, email, name, expiresAt: null, hasPlayback: false } }, 201, { 'set-cookie': sessionCookie(USER_COOKIE, value, 30 * 86400) });
  }
  if (action === 'auth/login' && request.method === 'POST') {
    const data = await body(request); if (!(await verifyTurnstile(data.turnstileToken, env, request))) return json({ error: '人机验证未通过' }, 403);
    const user = await env.LURI_MUSIC_DB.prepare('SELECT * FROM luri_music_users WHERE email=?').bind(cleanEmail(data.email)).first(); if (!user || !(await verifyPassword(data.password || '', user.password_hash))) return json({ error: '邮箱或密码错误' }, 401);
    const value = await createUserSession(user.id, env); const entitlement = await env.LURI_MUSIC_DB.prepare('SELECT expires_at FROM luri_music_entitlements WHERE user_id=?').bind(user.id).first(); return json({ user: publicUser({ ...user, expires_at: entitlement?.expires_at }) }, 200, { 'set-cookie': sessionCookie(USER_COOKIE, value, 30 * 86400) });
  }
  if (action === 'auth/logout' && request.method === 'POST') return json({ ok: true }, 200, { 'set-cookie': sessionCookie(USER_COOKIE, '', 0) });
  if (action === 'auth/password' && request.method === 'POST') { const user = await requireUser(request, env); const data = await body(request); if (!user) return json({ error: '请先登录' }, 401); if (!validPassword(data.password)) return json({ error: '密码至少 8 位' }, 400); await env.LURI_MUSIC_DB.prepare('UPDATE luri_music_users SET password_hash=?,updated_at=? WHERE id=?').bind(await passwordHash(data.password), now(), user.id).run(); return json({ ok: true }); }
  if (action === 'redeem' && request.method === 'POST') { const user = await requireUser(request, env); const data = await body(request); if (!user) return json({ error: '请先登录' }, 401); if (!(await verifyTurnstile(data.turnstileToken, env, request))) return json({ error: '人机验证未通过' }, 403); const code = String(data.code || '').replace(/[^A-Za-z0-9]/g, '').toUpperCase(); const record = await env.LURI_MUSIC_DB.prepare('SELECT * FROM luri_music_codes WHERE code_hash=?').bind(await hash(code)).first(); if (!record || record.disabled_at || record.redeemed_at || Date.parse(record.expires_at) <= Date.now()) return json({ error: '兑换码无效、已过期或已使用' }, 400); const current = await env.LURI_MUSIC_DB.prepare('SELECT expires_at FROM luri_music_entitlements WHERE user_id=?').bind(user.id).first(); const start = Math.max(Date.now(), Date.parse(current?.expires_at || 0)); const expires = new Date(start + record.duration_days * 864e5).toISOString(); await env.LURI_MUSIC_DB.batch([env.LURI_MUSIC_DB.prepare('UPDATE luri_music_codes SET redeemed_by=?,redeemed_at=? WHERE id=?').bind(user.id, now(), record.id), env.LURI_MUSIC_DB.prepare('INSERT INTO luri_music_entitlements(user_id,expires_at,updated_at) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET expires_at=excluded.expires_at,updated_at=excluded.updated_at').bind(user.id, expires, now())]); return json({ expiresAt: expires }); }
  if (action === 'admin/login' && request.method === 'POST') { const data = await body(request); const credential = await env.LURI_MUSIC_DB.prepare('SELECT password_hash FROM luri_music_admin_credentials WHERE id=1').first(); const valid = credential ? await verifyPassword(data.password || '', credential.password_hash) : Boolean(env.ADMIN_PASSWORD && data.password === env.ADMIN_PASSWORD); if (!valid) return json({ error: '密码错误' }, 401); if (!credential) await env.LURI_MUSIC_DB.prepare('INSERT INTO luri_music_admin_credentials(id,password_hash,updated_at) VALUES(1,?,?)').bind(await passwordHash(data.password), now()).run(); const value = token(); await env.LURI_MUSIC_DB.prepare('INSERT INTO luri_music_admin_sessions(id,token_hash,expires_at,created_at) VALUES(?,?,?,?)').bind(id(), await hash(value), new Date(Date.now() + 8 * 3600e3).toISOString(), now()).run(); return json({ ok: true }, 200, { 'set-cookie': sessionCookie(ADMIN_COOKIE, value, 8 * 3600) }); }
  if (!await adminSession(request, env)) return json({ error: '管理员登录已失效' }, 401);
  if (action === 'admin/status' && request.method === 'GET') { const setting = await env.LURI_MUSIC_DB.prepare("SELECT value FROM luri_music_settings WHERE key='music_enabled'").first(); const codes = await env.LURI_MUSIC_DB.prepare('SELECT id,duration_days,expires_at,redeemed_at,disabled_at,note,created_at FROM luri_music_codes ORDER BY created_at DESC LIMIT 100').all(); return json({ musicEnabled: setting?.value !== 'false', codes: codes.results }); }
  if (action === 'admin/codes' && request.method === 'POST') { const data = await body(request); const duration = Math.max(1, Math.min(3650, Number(data.durationDays) || 0)); const validDays = Math.max(1, Math.min(3650, Number(data.validDays) || 30)); if (!duration) return json({ error: '有效时长不正确' }, 400); const value = `LURI${token().slice(0, 12).toUpperCase()}`; await env.LURI_MUSIC_DB.prepare('INSERT INTO luri_music_codes(id,code_hash,duration_days,expires_at,note,created_at) VALUES(?,?,?,?,?,?)').bind(id(), await hash(value), duration, new Date(Date.now() + validDays * 864e5).toISOString(), String(data.note || '').slice(0, 120), now()).run(); return json({ code: value, durationDays: duration }); }
  if (action === 'admin/settings' && request.method === 'POST') { const data = await body(request); await env.LURI_MUSIC_DB.prepare("UPDATE luri_music_settings SET value=?,updated_at=? WHERE key='music_enabled'").bind(data.musicEnabled ? 'true' : 'false', now()).run(); return json({ ok: true }); }
  if (action === 'admin/password' && request.method === 'POST') { const data = await body(request); const credential = await env.LURI_MUSIC_DB.prepare('SELECT password_hash FROM luri_music_admin_credentials WHERE id=1').first(); if (!credential || !(await verifyPassword(data.currentPassword || '', credential.password_hash))) return json({ error: '当前密码错误' }, 400); if (!validPassword(data.newPassword)) return json({ error: '新密码至少需要 8 位' }, 400); await env.LURI_MUSIC_DB.prepare('UPDATE luri_music_admin_credentials SET password_hash=?,updated_at=? WHERE id=1').bind(await passwordHash(data.newPassword), now()).run(); return json({ ok: true }); }
  return json({ error: 'Not found' }, 404);
}
